various updates. still very early development.

diff --git a/.jcd-new/jcd-new-help b/.jcd-new/jcd-new-help
--- a/.jcd-new/jcd-new-help
+++ b/.jcd-new/jcd-new-help
@@ -1,4 +1,39 @@
 #!/bin/bash
+set -e
+get_script_dir () {
+     SOURCE="${BASH_SOURCE[0]}"
+     # While $SOURCE is a symlink, resolve it
+     while [ -h "$SOURCE" ]; do
+          DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
+          SOURCE="$( readlink "$SOURCE" )"
+          # If $SOURCE was a relative symlink (so no "/" as prefix, need to resolve it relative to the symlink base directory
+          [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
+     done
+     DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
+     echo "$DIR"
+}
+
+JCD_NEW_DIR=$(get_script_dir)
+
+if [[ "$1" == "" ]]; then
 echo "
-This is the help text
+usage: jcd-new [command] [command arguments]
+For more details on the individual commands type jcd-new help [command]
+
+List of commands:
+classlib   : creates a new classlib (netstandard2.1)
+
+help        : Displays this help information.
+
 "
+else
+
+    #( export GIT_VER_VERSION; "JCD_NEW_DIR/jcd-new-help-$1" 2>&1 /dev/null || { echo >&2 "Cannot find help for command: $1."; exit 1; } )
+    if [[ -f "$JCD_NEW_DIR/jcd-new-help-$1" ]]; then
+        ( export GIT_VER_VERSION; "$JCD_NEW_DIR/jcd-new-help-$1" )
+    else 
+        echo >&2 "Couldn't find help for: $1."; 
+        exit 1; 
+    fi;
+
+fi;
